spring:
  application:
     name: Library Mgmt App
  datasource:
    url: jdbc:h2:mem:libraryDb
  h2:
    console.enabled: true

springdoc:
  api-docs:
    path: /library-api-docs

server:
  port: 9090